version: '3'

services:
    rails:
        container_name: przepisy.rails
        build:
            context: ./
            dockerfile: Dockerfile
        networks:
            - global
        tty: true
        stdin_open: true
        ports:
            - 3011:3011
        labels:
            traefik.frontend.rule: "Host:api.przepisy.docker"
        volumes:
            - ./backend:/usr/src/app:cached
        restart: always
networks:
    global:
        external: true
